import NotificationsIcon from '@mui/icons-material/Notifications';
import CheckCircleIcon from '@mui/icons-material/CheckCircleOutline';
import MessageIcon from '@/assets/icons/notifications/chat-icon.svg';
import VisibilityIcon from '@mui/icons-material/Visibility';
import SystemUpdateAltIcon from '@/assets/icons/dashboard/icon-settings.svg';
import { frontUrls } from './front-urls';
import IconWork from '@/assets/icons/dashboard/cards/suitcase.svg';
import IconApplications from '@/assets/icons/dashboard/icon-applications.svg';
import UpdateIcon from '@mui/icons-material/Update';
import PhoneMissedIcon from '@mui/icons-material/PhoneMissed';
import IconMeets from '@/assets/icons/video-chat/meet-icon.svg';


export const NotificationTypeConfig = [
  {
    value: 'Job_Alert',
    label: 'Job Alert',
    Icon: NotificationsIcon,
    navigateTo: frontUrls.opportunities,
    visibleTo: ['Candidat', 'Recruteur'],
  },
  {
    value: 'Application_Status',
    label: 'Application Status',
    Icon: CheckCircleIcon,
    navigateTo: frontUrls.opportunities,
    visibleTo: ['Candidat'],
  },
  {
    value: 'Application_Sent',
    label: 'Application Sent',
    Icon: CheckCircleIcon, 
    navigateTo: frontUrls.myApplications,
    visibleTo: ['Candidat'],
  },
  {
    value: 'Message',
    label: 'New Message',
    Icon: MessageIcon,
    navigateTo: frontUrls.chat,
    visibleTo: ['Candidat', 'Recruteur'],
  },
  {
    value: 'Profile_Viewed',
    label: 'Profile Viewed',
    Icon: VisibilityIcon,
    navigateTo: frontUrls.account,
    visibleTo: ['Recruteur'],
  },
  {
    value: 'System',
    label: 'System Notification',
    Icon: SystemUpdateAltIcon,
    navigateTo: '',
    visibleTo: ['Candidat', 'Recruteur'],
  },
  {
    value: 'Opportunity_Created',
    label: 'Opportunity Created',
    Icon: IconWork,
    navigateTo: frontUrls.opportunities,
    visibleTo: ['Recruteur'],
  },
  {
    value: 'Opportunity_Archived',
    label: 'Opportunity Archived',
    Icon: UpdateIcon,
    navigateTo: frontUrls.opportunities,
    visibleTo: ['Recruteur'],
  },
  {
    value: 'Opportunity_Unarchived',
    label: 'Opportunity Unarchived',
    Icon: UpdateIcon,
    navigateTo: frontUrls.opportunities,
    visibleTo: ['Recruteur'],
  },
  {
    value: 'New Application',
    label: 'New Application',
    Icon: IconApplications,
    navigateTo: frontUrls.opportunities, 
    visibleTo: ['Recruteur'],
  },
  {
    value: 'Application_Status_Updated',
    label: 'Application Status Updated',
    Icon: UpdateIcon,
    navigateTo: frontUrls.applications,
    visibleTo: ['Candidat'],
  },
   {
    value: 'Call Missed',
    label: 'Call Missed',
    Icon: PhoneMissedIcon,
    // navigateTo: frontUrls.applications,
    visibleTo: ['Candidat'],
  },
  {
    value: 'INTERVIEW_SCHEDULED',
    label: 'Interview Scheduled',
    Icon: IconMeets,
    visibleTo: ['Candidat'],
  },
  {
    value: 'INTERVIEW_CANCELLED',
    label: 'Interview CANCELLED',
    Icon: IconMeets,
    visibleTo: ['Candidat'],
  },
];


export const NotificationReadOptions = [
  { label: 'All', value: '' },
  { label: 'Read', value: 'true' },
  { label: 'Unread', value: 'false' },
];
export const NotificationFavoriteOptions = [
  { label: 'All', value: '' },
  { label: 'Favorites', value: 'true' },
  { label: 'Non-Favorites', value: 'false' },
];
export const Role = {
  Admin: "Admin",
  Recruteur: "Recruteur",
  Candidat: "Candidat",
}

export const RoleWithoutAdmin = {
  Recruteur: "Recruteur",
  Candidat: "Candidat",
}

export const CandidateStatus = {
  New: 'New',
  Active: 'Active',
  Inactive: 'Inactive',
  Blacklisted: 'Blacklisted',
};
export const OpportunityTypeOptions = [
  { label: "Confidential", value: "Confidential" },
  { label: "Direct Hire", value: "Direct Hire" },
  { label: "Tender", value: "Tender" },
  { label: "Capability", value: "Capability" },
  { label: "Payroll", value: "Payroll" },
  { label: "In House", value: "In House" },
  { label: "Recrutement", value: "Recrutement" },
  { label: "Consulting", value: "Consulting" },
  { label: "Not specified", value: "Not specified" },
];

export const LegalStatus = {
  SARL: 'SARL',
  SA: 'SA',
  SAS: 'SAS',
  SASU: 'SASU',
  EURL: 'EURL',
  AUTO_ENTREPRENEUR: 'AUTO_ENTREPRENEUR',
  ONG: 'ONG',
  AUTRE: 'AUTRE',
};

export const LanguageLevels = {
  Elementary: "Elementary",
  LimitedWorking: "Limited working",
  ProfessionalWorking: "Professional working",
  FullProfessional: "Full professional",
  Native: "Native",
}

export const LanguageOptions = [
  "English",
  "French",
  "Spanish",
  "German",
  "Italian",
  "Portuguese",
  "Arabic",
  "Chinese",
  "Japanese",
  "Russian",
]
export const EmploymentTypes = [
  { value: "full_time", label: "Full-time" },
  { value: "part_time", label: "Part-time" },
];

export const WorkModes = [
  { value: "on_site", label: "On-site" },
  { value: "remote", label: "Remote" },
  { value: "hybrid", label: "Hybrid" },
];
export const urgentOpportunities = [
  { value: "true", label: "Urgent" },
  { value: "false", label: "Non urgent" },
];
export const isArchivedOpportunities = [
  { value: "true", label: "Archived" },
  { value: "false", label: "Non Archived" },
];

export const ContractTypes = [
  { value: "Permanent", label: "Permanent" },
  { value: "Fixed Term", label: "Fixed Term " },
  { value: "Freelance", label: "Freelance" },
  { value: "Temporary ", label: "Temporary " },
  { value: "Internship ", label: "Internship " },
  { value: "Apprenticeship ", label: "Apprenticeship" },
  { value: "Civic Service ", label: "Civic Service " },
  { value: "Other", label: "Other" },
];

export const Industry = {
  TRANSPORTATION: "Transportation",
  IT_TELECOM: "IT & Telecom",
  BANKING: "Banking",
  ENERGIES: "Energies",
  PHARMACEUTICAL: "Pharmaceutical",
  OTHER: "Other",
};

export const countryCodeMap = [
  'Afghanistan',
  'Åland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'AndorrA',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo, The Democratic Republic of the',
  'Cook Islands',
  'Costa Rica',
  "Cote D'Ivoire",
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Democratic Republic of the Congo',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and Mcdonald Islands',
  'Holy See (Vatican City State)',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran, Islamic Republic Of',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  "Korea, Democratic People'S Republic of",
  'Korea, Republic of',
  'Kuwait',
  'Kyrgyzstan',
  "Lao People'S Democratic Republic",
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia, The Former Yugoslav Republic of',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia, Federated States of',
  'Moldova, Republic of',
  'Monaco',
  'Mongolia',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'Netherlands Antilles',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russia',
  'RWANDA',
  'Saint Helena',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia and Montenegro',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela',
  'Viet Nam',
  'Virgin Islands, British',
  'Virgin Islands, U.S.',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe',
];

export const nameToCode = {
  France: 'fr',
  Morocco: 'ma',
  Italy: 'it',
  Germany: 'de',
  Spain: 'es',
  Tunisia: 'tn',
  Algeria: 'dz',
  Libya: 'ly',
  Egypt: 'eg',
  Senegal: 'sn',
  Afghanistan: 'af',
  Albania: 'al',
  Andorra: 'ad',
  Angola: 'ao',
  Argentina: 'ar',
  Armenia: 'am',
  Australia: 'au',
  Austria: 'at',
  Azerbaijan: 'az',
  Bahamas: 'bs',
  Bahrain: 'bh',
  Bangladesh: 'bd',
  Barbados: 'bb',
  Belarus: 'by',
  Belgium: 'be',
  Belize: 'bz',
  Benin: 'bj',
  Bhutan: 'bt',
  Bolivia: 'bo',
  'Bosnia and Herzegovina': 'ba',
  Botswana: 'bw',
  Brazil: 'br',
  Brunei: 'bn',
  Bulgaria: 'bg',
  'Burkina Faso': 'bf',
  Burundi: 'bi',
  Cambodia: 'kh',
  Cameroon: 'cm',
  Canada: 'ca',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  Chad: 'td',
  Chile: 'cl',
  China: 'cn',
  Colombia: 'co',
  Comoros: 'km',
  Congo: 'cg',
  'Costa Rica': 'cr',
  Croatia: 'hr',
  Cuba: 'cu',
  Cyprus: 'cy',
  'Czech Republic': 'cz',
  Denmark: 'dk',
  Djibouti: 'dj',
  Dominica: 'dm',
  'Dominican Republic': 'do',
  Ecuador: 'ec',
  'El Salvador': 'sv',
  'Equatorial Guinea': 'gq',
  Eritrea: 'er',
  Estonia: 'ee',
  Eswatini: 'sz',
  Ethiopia: 'et',
  Fiji: 'fj',
  Finland: 'fi',
  Gabon: 'ga',
  Gambia: 'gm',
  Georgia: 'ge',
  Ghana: 'gh',
  Greece: 'gr',
  Greenland: 'gl',
  Grenada: 'gd',
  Guatemala: 'gt',
  Guinea: 'gn',
  'Guinea-Bissau': 'gw',
  Guyana: 'gy',
  Haiti: 'ht',
  Honduras: 'hn',
  Hungary: 'hu',
  Iceland: 'is',
  India: 'in',
  Indonesia: 'id',
  Iran: 'ir',
  Iraq: 'iq',
  Ireland: 'ie',
  Israel: 'il',
  Jamaica: 'jm',
  Japan: 'jp',
  Jordan: 'jo',
  Kazakhstan: 'kz',
  Kenya: 'ke',
  Kiribati: 'ki',
  Korea: 'kr',
  Kuwait: 'kw',
  Kyrgyzstan: 'kg',
  Laos: 'la',
  Latvia: 'lv',
  Lebanon: 'lb',
  Lesotho: 'ls',
  Liberia: 'lr',
  Liechtenstein: 'li',
  Lithuania: 'lt',
  Luxembourg: 'lu',
  Madagascar: 'mg',
  Malawi: 'mw',
  Malaysia: 'my',
  Maldives: 'mv',
  Mali: 'ml',
  Malta: 'mt',
  'Marshall Islands': 'mh',
  Mauritania: 'mr',
  Mauritius: 'mu',
  Mexico: 'mx',
  Micronesia: 'fm',
  Moldova: 'md',
  Monaco: 'mc',
  Mongolia: 'mn',
  Montenegro: 'me',
  Morocco: 'ma',
  Mozambique: 'mz',
  Myanmar: 'mm',
  Namibia: 'na',
  Nauru: 'nr',
  Nepal: 'np',
  Netherlands: 'nl',
  'New Zealand': 'nz',
  Nicaragua: 'ni',
  Niger: 'ne',
  Nigeria: 'ng',
  'North Macedonia': 'mk',
  Norway: 'no',
  Oman: 'om',
  Pakistan: 'pk',
  Palau: 'pw',
  Panama: 'pa',
  'Papua New Guinea': 'pg',
  Paraguay: 'py',
  Peru: 'pe',
  Philippines: 'ph',
  Poland: 'pl',
  Portugal: 'pt',
  Qatar: 'qa',
  Romania: 'ro',
  Russia: 'ru',
  Rwanda: 'rw',
  'Saint Kitts and Nevis': 'kn',
  'Saint Lucia': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  Samoa: 'ws',
  'San Marino': 'sm',
  'Sao Tome and Principe': 'st',
  'Saudi Arabia': 'sa',
  Senegal: 'sn',
  Serbia: 'rs',
  Seychelles: 'sc',
  'Sierra Leone': 'sl',
  Singapore: 'sg',
  Slovakia: 'sk',
  Slovenia: 'si',
  'Solomon Islands': 'sb',
  Somalia: 'so',
  'South Africa': 'za',
  Spain: 'es',
  'Sri Lanka': 'lk',
  Sudan: 'sd',
  Suriname: 'sr',
  Sweden: 'se',
  Switzerland: 'ch',
  Syria: 'sy',
  Taiwan: 'tw',
  Tajikistan: 'tj',
  Tanzania: 'tz',
  Thailand: 'th',
  Togo: 'tg',
  Tonga: 'to',
  'Trinidad and Tobago': 'tt',
  Tunisia: 'tn',
  Turkey: 'tr',
  Turkmenistan: 'tm',
  Tuvalu: 'tv',
  Uganda: 'ug',
  Ukraine: 'ua',
  'United Arab Emirates': 'ae',
  'United Kingdom': 'gb',
  'United States': 'us',
  Uruguay: 'uy',
  Uzbekistan: 'uz',
  Vanuatu: 'vu',
  Venezuela: 've',
  Vietnam: 'vn',
  Yemen: 'ye',
  Zambia: 'zm',
  Zimbabwe: 'zw'
};

export const visibilityOptions = [
  { value: 'Public', label: 'Public' },
  { value: 'Private', label: 'Private' },
  { value: 'Draft', label: 'Draft' },
];
export const applicationStatisOptions = [
  { value: 'Pending', label: 'Pending' },
  { value: 'Accepted', label: 'Accepted' },
  { value: 'Rejected', label: 'Rejected' },
];
export const applicationStatisAfterMeetOptions = [
  { value: 'Accepted', label: 'Accepted' },
  { value: 'Rejected', label: 'Rejected' },
];
export const jobStatusOptions = [
  { value: 'Active', label: 'Active' },
  { value: 'Expired', label: 'Expired' },
];

export const industryOptions = Object.entries(Industry).map(([key, value]) => ({
  value,
  label: value,
}));

export const countryOptions = countryCodeMap.map((country) => ({
  value: country,
  label: country,
}));
export const cityOptions = [
  { label: "Tunis", value: "Tunis" },
  { label: "Nabeul", value: "Nabeul" },
];
export const companySizeOptions = [
  { value: '1-10', label: '1-10 employees' },
  { value: '11-50', label: '11-50 employees' },
  { value: '51-200', label: '51-200 employees' },
  { value: '201-500', label: '201-500 employees' },
  { value: '501-1000', label: '501-1000 employees' },
  { value: '1001-5000', label: '1001-5000 employees' },
  { value: '5001-10000', label: '5001-10000 employees' },
  { value: '10000+', label: '10,000+ employees' },
];

export function getCountryCode(countryName) {
  return nameToCode[countryName] || '';
}

export function getCountryFlagUrl(countryName) {
  const code = getCountryCode(countryName);
  return code ? `https://flagcdn.com/w40/${code}.png` : '';
}

export const interestStatusOptions = [
  { label: 'Interested', value: 'Interested' },
  { label: 'Maybe', value: 'Maybe' },
  { label: 'Not Interested', value: 'Not Interested' },
];


