
export const frontUrls ={
    login: "/login",
    register: "/register",
    users: "/users",
    updatepassword: "/updatepassword",
    account: "/account",
    forgotpassword: "/forgot-password",
    dashboard: "/dashboard/home",
    myApplications: "/dashboard/my-applications",
    chat: "/messages",
    settings: "/settings",
    helpcenter: "/helpcenter",
    chooseRole: "/choose-role",
    notifications: "/notifications",
    opportunities: "/opportunities",
    addOpportunity: '/opportunities/add',
    applications: "/applications",
    videochat: '/video-chat',
    myFavorites: '/favorite-opportunities',
    myResumes: '/my-resumes',
    resume: '/cv-video',
    notifications: '/notifications',
    globe3D: '/globe3D',
    interviews: '/video-chat',
    schInterviews: '/interviews-calendar',
    addUser: '/add-user',
    interviewsList: '/interviews-list-candidate'
}