
export const updatePasswordFields = [
    {
        name: "currentPassword",
        label: "Current Password",
        type: "password",
        placeholder: "Your current password",
        required: true,
    },
    {
        name: "newPassword",
        label: "New password",
        type: "password",
        placeholder: "Your new password",
        required: true,
    }, 
    {
        name: "confirmNewPassword",
        label: "Confirm Password",
        placeholder: "Your new password confirmation",
        type: "password",
        required: true,
    },
];
export const qrCodeFields = [
    {
        name: "twoFactorCode",
        label: "",
        type: "text",
        placeholder: "Enter the code generated by the app",
        required: true,
    },
]
